version: "3.9"
services:
  postgres:
    image: postgres:15.3 
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - ./pgdata:/var/lib/postgres/data
    ports:
      - 5432:5432
